; This file is contain all config for this skin
;   - Author: Luna-Hibiki
;   - Date:   24-5-2022
;   - Note: Please don't edit this file. You can edit the skin via setting.
[Variables]
flower_resmon_drive_0 = C:
flower_resmon_drive_1 = G:
flower_resmon_title_font_name = Patrick Hand SC
flower_resmon_title_font_size = 10
flower_resmon_title_font_color = ffffff
flower_resmon_bar_width = 80
flower_resmon_bar_height = 8
flower_resmon_bar_color_0 = 00000040
flower_resmon_bar_color_1 = ffffff