; Change these variables to your desired setup

[Variables]
; The color of the sliding bars background
BgColor        = 58,90,111,50
; The color of the icons (Set this to 255,255,255 if your icons have color)
IconColor      = 255,255,255,255
; The amount of icons to show on each of the top & bottom slide bars
; "Do not forget to change this after you add more icons to the dock"
IconsToShowTop = 1
IconsToShowBot = -1

; Save your icons inside the "@Resources\Icons" folder
; IconName  >> The name of the icon file saved in the icons folder (Ex: steam.png)
; IconPath  >> The path of the app that you want to launch (Ex: C:\Program Files (x86)\Steam\Steam.exe)

;========= Mid Icons =========
MidIconName1 = directory.ico
MidIconPath1 = "C:\Users\ArminC\Directory"

MidIconName2 = this_pc.ico
MidIconPath2 = "C:\Windows\This PC.lnk"
  
MidIconName3 = recycle_bin.ico
MidIconPath3 = "C:\Windows\Recycle Bin.lnk"

;========= Top Icons =========

TopIconName1 = winutil.ico
TopIconPath1 = "C:\Windows\winutil.bat"
  
TopIconName2 =
TopIconPath2 = 
  
TopIconName3 =
TopIconPath3 =
 
TopIconName4 =
TopIconPath4 =
 
TopIconName5 =
TopIconPath5 =

;========= Bottom Icons =========

BottomIconName1 = icon.png
BottomIconPath1 = 
  
BottomIconName2 = icon.png
BottomIconPath2 = 
  
BottomIconName3 = icon.png
BottomIconPath3 =
 
BottomIconName4 =
BottomIconPath4 =
 
BottomIconName5 =
BottomIconPath5 =

